language: php

php:
  - 5.6
  - 7.0

before_script:
  - npm install -g sass-lint
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - sass-lint -c .sass-lint.yml '**/*.scss' -v -q
